### ISSUE TITLE
thread 'tokio-runtime-worker' panicked at 'assertion failed: pack_size(n) <= nbytes && nbytes <= 8'

### ISSUE THREAD

**Issue by peteriscan** [akula-bft/akula#212]
I'm syncing goerli.

Version: 74b172ee1d2d2a4f04ce057b5a76679c1b83df9c (c0422ece8d35e14d2034a5298e0e4801a78198e3 in my fork)

Command:

```
akula --chain=goerli --datadir=/ethclient/akula --rpc-listen-address=0.0.0.0:8545 --max-peers=100 --listen-port=30303 --discv4-port=30303
```

Error:

```
2022-07-23T09:23:58.857364Z  INFO { 7/14 Execution }: Executed block 5991478, Mgas/sec: 719.43, progress: 52.36%, 02:26:38 remaining
2022-07-23T09:24:28.860939Z  INFO { 7/14 Execution }: Executed block 6004735, Mgas/sec: 716.36, progress: 52.53%, 02:26:06 remaining
2022-07-23T09:24:58.868524Z  INFO { 7/14 Execution }: Executed block 6018504, Mgas/sec: 768.32, progress: 52.71%, 02:25:29 remaining
2022-07-23T09:25:28.869072Z  INFO { 7/14 Execution }: Executed block 6027435, Mgas/sec: 663.73, progress: 52.87%, 02:25:00 remaining
thread 'tokio-runtime-worker' panicked at 'assertion failed: pack_size(n) <= nbytes && nbytes <= 8', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/byteorder-1.4.3/src/lib.rs:2043:9
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
2022-07-23T09:26:00.361244Z  INFO Starting Akula (akula/v0.1.0-dockerfile-c0422ec-2022-07-22/x86_64-unknown-linux-gnu/rustc1.63.0-nightly)
```

Happened 3 times.

with `RUST_BACKTRACE=1`

```
2022-07-23T09:49:53.312351Z  INFO { 7/14 Execution }: Executed block 5098517, Mgas/sec: 844.93, progress: 2.64%, 03:04:10 remaining
thread 'tokio-runtime-worker' panicked at 'assertion failed: pack_size(n) <= nbytes && nbytes <= 8', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/byteorder-1.4.3/src/lib.rs:2043:9
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/c3b7d7b496b5536bb0a3d501222d2d0a8b54a69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/c3b7d7b496b5536bb0a3d501222d2d0a8b54a69e/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at ./rustc/c3b7d7b496b5536bb0a3d501222d2d0a8b54a69e/library/core/src/panicking.rs:48:5
   3: <akula::sentry::devp2p::ecies::proto::ECIESCodec as tokio_util::codec::encoder::Encoder<akula::sentry::devp2p::ecies::proto::EgressECIESValue>>::encode
   4: <akula::sentry::devp2p::peer::PeerStream<Io> as futures_sink::Sink<akula::sentry::devp2p::peer::PeerMessage>>::start_send
   5: tokio::runtime::task::core::CoreStage<T>::poll
   6: tokio::runtime::task::raw::poll
   7: tokio::runtime::thread_pool::worker::Context::run_task
   8: tokio::runtime::task::raw::poll
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

wtih `RUST_BACKTRACE=full`

```
2022-07-23T10:14:16.330838Z  INFO { 7/14 Execution }: Executed block 5458107, Mgas/sec: 1007.83, progress: 10.76%, 02:25:15 remaining
2022-07-23T10:14:21.306028Z  WARN No records found for tree all.goerli.ethdisco.net
2022-07-23T10:14:31.309397Z  WARN No records found for tree all.goerli.ethdisco.net
thread 'tokio-runtime-worker' panicked at 'assertion failed: pack_size(n) <= nbytes && nbytes <= 8', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/byteorder-1.4.3/src/lib.rs:2043:9
stack backtrace:
   0:     0x55a357321af1 - std::backtrace_rs::backtrace::libunwind::trace::hf89908ee4ef62dcb
                               at /rustc/c3b7d7b496b5536bb0a3d501222d2d0a8b54a69e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55a357321af1 - std::backtrace_rs::backtrace::trace_unsynchronized::hdd52d0d3b01872ce
                               at /rustc/c3b7d7b496b5536bb0a3d501222d2d0a8b54a69e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55a357321af1 - std::sys_common::backtrace::_print_fmt::h061c43939c546e99
                               at /rustc/c3b7d7b496b5536bb0a3d501222d2d0a8b54a69e/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55a357321af1 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2ad1839a95717671
                               at /rustc/c3b7d7b496b5536bb0a3d501222d2d0a8b54a69e/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55a35719946c - core::fmt::write::hcc163458a1d38ffc
                               at /rustc/c3b7d7b496b5536bb0a3d501222d2d0a8b54a69e/library/core/src/fmt/mod.rs:1196:17
   5:     0x55a3572fcc64 - std::io::Write::write_fmt::h61843d38e4d3e1e4
                               at /rustc/c3b7d7b496b5536bb0a3d501222d2d0a8b54a69e/library/std/src/io/mod.rs:1654:15
   6:     0x55a357322896 - std::sys_common::backtrace::_print::h529125dd665392c1
                               at /rustc/c3b7d7b496b5536bb0a3d501222d2d0a8b54a69e/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55a357322896 - std::sys_common::backtrace::print::hdba5ca9bd3755587
                               at /rustc/c3b7d7b496b5536bb0a3d501222d2d0a8b54a69e/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55a357322896 - std::panicking::default_hook::{{closure}}::h934274babbd24a8b
                               at /rustc/c3b7d7b496b5536bb0a3d501222d2d0a8b54a69e/library/std/src/panicking.rs:295:22
   9:     0x55a3573238c1 - std::panicking::default_hook::he71622e2d2c96e2b
                               at /rustc/c3b7d7b496b5536bb0a3d501222d2d0a8b54a69e/library/std/src/panicking.rs:314:9
  10:     0x55a3573238c1 - std::panicking::rust_panic_with_hook::h34610951dc8d08fd
                               at /rustc/c3b7d7b496b5536bb0a3d501222d2d0a8b54a69e/library/std/src/panicking.rs:698:17
  11:     0x55a35732339b - std::panicking::begin_panic_handler::{{closure}}::hfe33f84157df7a54
                               at /rustc/c3b7d7b496b5536bb0a3d501222d2d0a8b54a69e/library/std/src/panicking.rs:586:13
  12:     0x55a357323336 - std::sys_common::backtrace::__rust_end_short_backtrace::h2ee1b7705efa3322
                               at /rustc/c3b7d7b496b5536bb0a3d501222d2d0a8b54a69e/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x55a3573232f2 - rust_begin_unwind
                               at /rustc/c3b7d7b496b5536bb0a3d501222d2d0a8b54a69e/library/std/src/panicking.rs:584:5
  14:     0x55a3568c33e2 - core::panicking::panic_fmt::h190441860093e4f6
                               at /rustc/c3b7d7b496b5536bb0a3d501222d2d0a8b54a69e/library/core/src/panicking.rs:142:14
  15:     0x55a3568c34dc - core::panicking::panic::he348677785da248a
                               at /rustc/c3b7d7b496b5536bb0a3d501222d2d0a8b54a69e/library/core/src/panicking.rs:48:5
  16:     0x55a357125021 - <akula::sentry::devp2p::ecies::proto::ECIESCodec as tokio_util::codec::encoder::Encoder<akula::sentry::devp2p::ecies::proto::EgressECIESValue>>::encode::h4b552c5fc80a2637
  17:     0x55a356948712 - <akula::sentry::devp2p::peer::PeerStream<Io> as futures_sink::Sink<akula::sentry::devp2p::peer::PeerMessage>>::start_send::hfb43a6c605e8b9a0
  18:     0x55a356cfc102 - tokio::runtime::task::core::CoreStage<T>::poll::hb8b0a9f1dbd48a35
  19:     0x55a356cd4b77 - tokio::runtime::task::raw::poll::hd07f983a60d046f3
  20:     0x55a357347939 - tokio::runtime::thread_pool::worker::Context::run_task::h3b651e3470a4587a
  21:     0x55a357345530 - tokio::runtime::task::raw::poll::h530f85edd88e528d
  22:     0x55a3573393e2 - std::sys_common::backtrace::__rust_begin_short_backtrace::hcd4cf0a566e25904
  23:     0x55a3573391fe - core::ops::function::FnOnce::call_once{{vtable.shim}}::h8b67bd491ac011f5
  24:     0x55a357324eb5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd8b656a9374bcd8e
                               at /rustc/c3b7d7b496b5536bb0a3d501222d2d0a8b54a69e/library/alloc/src/boxed.rs:1951:9
  25:     0x55a357324eb5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hef0b89bb63f23988
                               at /rustc/c3b7d7b496b5536bb0a3d501222d2d0a8b54a69e/library/alloc/src/boxed.rs:1951:9
  26:     0x55a357324eb5 - std::sys::unix::thread::Thread::new::thread_start::h844378c31cddf48e
                               at /rustc/c3b7d7b496b5536bb0a3d501222d2d0a8b54a69e/library/std/src/sys/unix/thread.rs:108:17
  27:     0x7f8d0eaadea7 - start_thread
  28:     0x7f8d0e893def - clone
  29:                0x0 - <unknown>
```

**Comment by vorot93** [comment]
Should be fixed in master
